### ISSUE TITLE
Alignment for Nested Grids

### ISSUE THREAD

**Issue by PatrickKutch** [intel/Board-Instrumentation-Framework#6]
So if I have a grid or dynamic grid that contains a grid, a spacer and a grid with the grids and spacer all being different sizes. say 100x100,20,20,140,100
and all are aligned north, the spacer will be Noth, but the left cell won't be.

**Comment by thehevy** [comment]
Work around:

Only put one row in the grid without setting a height on the internal grids. They will all set to 100% height and align

Sent from my iPhone

On May 24, 2019, at 8:41 AM, Patrick Kutch <notifications@github.com<mailto:notifications@github.com>> wrote:


So if I have a grid or dynamic grid that contains a grid, a spacer and a grid with the grids and spacer all being different sizes. say 100x100,20,20,140,100
and all are aligned north, the spacer will be Noth, but the left cell won't be.

**Comment by PatrickKutch** [comment]
I think it works as designed.  A grid by default takes up the entire cell it is in, unless surrounding cells are larger in one dimension or the other.
